#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_approx.hpp>
#include <sovereign/qp.hpp>
using namespace sovereign; using Catch::Approx;
namespace { QuadraticModel unconstrained(double q,double c) { QuadraticModel p; p.linear.name="quadratic"; p.linear.variables={{"x",-infinity,infinity}}; p.linear.objective={c}; p.linear.matrix=CscMatrix::from_triplets(0,1,{}); p.quadratic=CscMatrix::from_triplets(1,1,{{0,0,q}}); return p; } }
TEST_CASE("interior point solves a hand-verifiable unconstrained convex QP","[qp]") { const auto r=solve_qp(unconstrained(2,-4)); INFO(r.message); REQUIRE(r.status==SolveStatus::optimal); REQUIRE(r.primal[0]==Approx(2).margin(1e-7)); REQUIRE(r.objective==Approx(-4).margin(1e-7)); REQUIRE(r.verification.passed); }
TEST_CASE("interior point respects variable and row bounds","[qp]") { auto p=unconstrained(2,-6); p.linear.variables[0].lower=0; p.linear.variables[0].upper=2; p.linear.constraints={{"floor",1.5,infinity}}; p.linear.matrix=CscMatrix::from_triplets(1,1,{{0,0,1}}); const auto r=solve_qp(p); INFO(r.message); REQUIRE(r.status==SolveStatus::optimal); REQUIRE(r.primal[0]==Approx(2).margin(2e-5)); REQUIRE(r.objective==Approx(-8).margin(2e-5)); REQUIRE(r.verification.passed); }
TEST_CASE("interior point LP path solves a bounded linear model","[qp][lp]") { Model m; m.variables={{"x",0,infinity},{"y",0,infinity}}; m.objective={-1,-2}; m.constraints={{"capacity",-infinity,4}}; m.matrix=CscMatrix::from_triplets(1,2,{{0,0,1},{0,1,1}}); const auto r=solve_interior_point(m); INFO(r.message); REQUIRE(r.status==SolveStatus::optimal); REQUIRE(r.objective==Approx(-8).margin(2e-5)); REQUIRE(r.verification.passed); }
TEST_CASE("QP rejects a nonsymmetric or nonconvex Hessian","[qp]") { auto p=unconstrained(-1,0); REQUIRE(solve_qp(p).status==SolveStatus::numerical_failure); p.linear.variables.push_back({"y",-infinity,infinity}); p.linear.objective.push_back(0); p.linear.matrix=CscMatrix::from_triplets(0,2,{}); p.quadratic=CscMatrix::from_triplets(2,2,{{0,1,1}}); REQUIRE(solve_qp(p).status==SolveStatus::numerical_failure); }
TEST_CASE("interior point handles a concave maximization QP","[qp]") { auto p=unconstrained(-2,4); p.linear.sense=ObjectiveSense::maximize; const auto r=solve_qp(p); INFO(r.message); REQUIRE(r.status==SolveStatus::optimal); REQUIRE(r.primal[0]==Approx(2).margin(1e-7)); REQUIRE(r.objective==Approx(4).margin(1e-7)); REQUIRE(r.verification.passed); }
TEST_CASE("QP certificate is independently reverified and corruption is rejected","[qp][verification]") { auto p=unconstrained(2,-6);p.linear.variables[0].lower=0;p.linear.variables[0].upper=2;const auto solved=solve_qp(p);REQUIRE(solved.status==SolveStatus::optimal);REQUIRE(verify_qp_optimality(p,solved.primal,solved.objective,solved.certificate).passed);auto bad=solved.certificate;bad.variable_upper[0]+=1;REQUIRE_FALSE(verify_qp_optimality(p,solved.primal,solved.objective,bad).passed); }
