* Hand-counted: 2 variables, 2 rows, 4 matrix nonzeros.
NAME SMALL_LP
OBJSENSE
 MAX
ROWS
 N PROFIT
 L CAPACITY
 L RESOURCE
COLUMNS
 x PROFIT 3 CAPACITY 1
 x RESOURCE 2
 y PROFIT 2 CAPACITY 1
 y RESOURCE 1
RHS
 rhs CAPACITY 4 RESOURCE 5
ENDATA
