import { useEffect,useState,type FormEvent } from 'react'
import { api,pollJob,type AiProposalData,type BenchmarkResult,type Job,type ModelInfo,type ServiceStatus,type TelemetryPoint } from './api'
import { AiProposal,EmptyState,Metric,Panel,ServiceState,TelemetryChart } from './components'

const views=['Dashboard','Upload','Model Inspector','Fingerprint','Solver Configuration','Live Solve','Benchmark Laboratory','Verification','AI Assistant','Documentation'] as const
type View=typeof views[number]
const icons=['⌂','⇧','▤','⌁','⚙','▶','▥','✓','✦','?']

export default function App(){
 const [view,setView]=useState<View>('Dashboard'),[online,setOnline]=useState(false),[gpu,setGpu]=useState<ServiceStatus>('checking'),[ai,setAi]=useState<ServiceStatus>('checking')
 const [models,setModels]=useState<ModelInfo[]>([]),[model,setModel]=useState<ModelInfo|null>(null),[job,setJob]=useState<Job|null>(null),[telemetry,setTelemetry]=useState<TelemetryPoint[]>([]),[notice,setNotice]=useState('')
 useEffect(()=>{api.health().then(h=>{setOnline(true);setGpu(status(h.gpu));setAi(status(h.ai))}).catch(()=>{setGpu('unavailable');setAi('unavailable')});api.models().then(ms=>{setModels(ms);setModel(ms[0]||null)}).catch(()=>{})},[])
 const startSolve=async(options:Record<string,unknown>)=>{if(!model)return;try{const j=await api.solve(model.id,options);setJob(j);setTelemetry([]);setView('Live Solve');pollJob(j.id,async next=>{setJob(next);api.telemetry(j.id).then(setTelemetry).catch(()=>{})}).catch(e=>setNotice(message(e)))}catch(e){setNotice(message(e))}}
 return <div className="app"><aside><div className="brand"><div className="mark">S</div><div><b>SOVEREIGN</b><span>OPTIMIZATION LAB</span></div></div><nav aria-label="Primary">{views.map((v,i)=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}><i>{icons[i]}</i>{v}</button>)}</nav><div className="aside-status"><ServiceState service="API" status={online?'available':'unavailable'} detail={online?'Connected':'Server unreachable'}/><small>ENGINEERING CONSOLE · VERIFIED CORE</small></div></aside><main><Topbar view={view} model={model}/>{notice&&<div className="notice" role="alert">{notice}<button aria-label="Dismiss" onClick={()=>setNotice('')}>×</button></div>}<div className="content">{renderView(view,{online,gpu,ai,models,model,setModel,setModels,job,telemetry,startSolve,setView,setNotice})}</div></main></div>
}
const status=(x:unknown):ServiceStatus=>x===true?'available':x===false?'unavailable':['available','degraded','unavailable'].includes(String(x))?x as ServiceStatus:'checking'
const message=(e:unknown)=>e instanceof Error?e.message:'Unexpected request failure'
function Topbar({view,model}:{view:View;model:ModelInfo|null}){return <header className="topbar"><div><p className="kicker">WORKSPACE / {view.toUpperCase()}</p><h1>{view}</h1></div><div className="model-chip"><span>ACTIVE MODEL</span><b>{model?.name||'None loaded'}</b></div></header>}
type Ctx={online:boolean;gpu:ServiceStatus;ai:ServiceStatus;models:ModelInfo[];model:ModelInfo|null;setModel:(m:ModelInfo|null)=>void;setModels:(m:ModelInfo[])=>void;job:Job|null;telemetry:TelemetryPoint[];startSolve:(o:Record<string,unknown>)=>void;setView:(v:View)=>void;setNotice:(s:string)=>void}
function renderView(v:View,c:Ctx){switch(v){case'Dashboard':return <Dashboard {...c}/>;case'Upload':return <Upload {...c}/>;case'Model Inspector':return <Inspector {...c}/>;case'Fingerprint':return <Fingerprint {...c}/>;case'Solver Configuration':return <Config {...c}/>;case'Live Solve':return <Live {...c}/>;case'Benchmark Laboratory':return <Benchmark {...c}/>;case'Verification':return <Verification {...c}/>;case'AI Assistant':return <Assistant {...c}/>;default:return <Docs/>}}

function Dashboard(c:Ctx){return <><div className="hero"><div><p className="kicker">SYSTEM OVERVIEW</p><h2>Optimization control surface</h2><p>Inspect models, run measured solver experiments, and verify every result from one audit-oriented workspace.</p></div><button onClick={()=>c.setView('Upload')}>Upload MPS <span>→</span></button></div><div className="metric-grid"><Metric label="MODELS" value={c.models.length}/><Metric label="ACTIVE JOB" value={c.job?.status.toUpperCase()||'NONE'}/><Metric label="OBJECTIVE" value={String(c.job?.result?.objective??'—')}/><Metric label="MIP GAP" value={c.telemetry.at(-1)?.gap} unit="%"/></div><div className="two-col"><Panel title="Convergence trace" kicker="LIVE TELEMETRY"><TelemetryChart points={c.telemetry} series={[{key:'incumbent',label:'Incumbent'},{key:'bound',label:'Best bound'}]}/></Panel><Panel title="Compute services" kicker="RUNTIME"><div className="services"><ServiceState service="FastAPI" status={c.online?'available':'unavailable'} detail={c.online?'Job API responding':'Start the API service to enable operations'}/><ServiceState service="CUDA" status={c.gpu} detail={c.gpu==='unavailable'?'No compatible GPU service detected':'Hardware acceleration status'}/><ServiceState service="Mistral" status={c.ai} detail={c.ai==='unavailable'?'AI explanations are optional and unavailable':'Optional, non-authoritative assistant'}/></div></Panel></div></>}

function Upload(c:Ctx){const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();if(!file)return;setBusy(true);try{const m=await api.upload(file);c.setModels([...c.models,m]);c.setModel(m);c.setView('Model Inspector')}catch(e){c.setNotice(message(e))}finally{setBusy(false)}};return <Panel title="Import mathematical program" kicker="MPS INGESTION"><form className="upload" onSubmit={submit}><label className="drop"><input type="file" accept=".mps,.mps.gz" onChange={e=>setFile(e.target.files?.[0]||null)}/><span>⇧</span><b>{file?.name||'Drop an MPS file or browse'}</b><small>Validated by the server before entering the model registry</small></label><button disabled={!file||busy}>{busy?'Uploading…':'Upload and inspect'}</button></form></Panel>}
function Inspector(c:Ctx){if(!c.model)return <EmptyState title="No model loaded" detail="Upload an MPS file to inspect its mathematical structure."/>;return <><div className="metric-grid"><Metric label="VARIABLES" value={c.model.variables}/><Metric label="CONSTRAINTS" value={c.model.constraints}/><Metric label="NONZEROS" value={c.model.nonzeros}/><Metric label="SENSE" value={c.model.sense?.toUpperCase()}/></div><Panel title={c.model.name} kicker="MODEL REGISTRY"><dl className="details"><dt>Model ID</dt><dd>{c.model.id}</dd><dt>Format</dt><dd>{c.model.format||'MPS'}</dd><dt>Fingerprint</dt><dd className="mono">{c.model.fingerprint||'Not computed'}</dd></dl></Panel></>}
function Fingerprint(c:Ctx){const [data,setData]=useState<Record<string,unknown>|null>(null);if(!c.model)return <EmptyState title="No model selected" detail="A fingerprint is computed from an uploaded model."/>;return <Panel title="Structural fingerprint" kicker="DETERMINISTIC ANALYSIS" actions={<button onClick={()=>api.fingerprint(c.model!.id).then(setData).catch(e=>c.setNotice(message(e)))}>Compute</button>}>{data?<pre className="json">{JSON.stringify(data,null,2)}</pre>:<EmptyState title="Fingerprint not computed" detail="Run analysis to measure structural features without solving."/>}</Panel>}
function Config(c:Ctx){const [backend,setBackend]=useState('adaptive'),[time,setTime]=useState(300),[gap,setGap]=useState(.01);return <Panel title="Solver controls" kicker="EXECUTION POLICY"><div className="form-grid"><label>Backend<select value={backend} onChange={e=>setBackend(e.target.value)}><option value="adaptive">Adaptive</option><option value="cpu">CPU</option><option value="gpu" disabled={c.gpu==='unavailable'}>GPU {c.gpu==='unavailable'?'(unavailable)':''}</option></select></label><label>Time limit (seconds)<input type="number" min="1" value={time} onChange={e=>setTime(+e.target.value)}/></label><label>Relative MIP gap<input type="number" min="0" step="0.001" value={gap} onChange={e=>setGap(+e.target.value)}/></label></div><div className="actionbar"><span>{c.model?`Ready: ${c.model.name}`:'Select a model before solving'}</span><button disabled={!c.model} onClick={()=>c.startSolve({kind:(c.model?.integer_variables||0)>0?'mip':'lp',backend,time_limit_seconds:time,mip_gap:gap})}>Start solve →</button></div></Panel>}
function Live(c:Ctx){return <><div className="metric-grid"><Metric label="STATE" value={c.job?.status.toUpperCase()||'IDLE'}/><Metric label="ELAPSED" value={c.telemetry.at(-1)?.elapsed} unit="s"/><Metric label="NODES" value={c.telemetry.at(-1)?.nodes}/><Metric label="GAP" value={c.telemetry.at(-1)?.gap} unit="%"/></div><Panel title="Incumbent and bound" kicker="CONVERGENCE"><TelemetryChart points={c.telemetry} series={[{key:'incumbent',label:'Incumbent'},{key:'bound',label:'Best bound'},{key:'gap',label:'Gap'}]}/></Panel><Panel title="Resource telemetry" kicker="MEASURED UTILIZATION"><TelemetryChart points={c.telemetry} series={[{key:'nodes',label:'Nodes'},{key:'cpu',label:'CPU'},{key:'gpu',label:'GPU'}]}/></Panel></>}
function Benchmark(c:Ctx){const [results,setResults]=useState<BenchmarkResult[]>([]),[running,setRunning]=useState(false);const run=async()=>{if(!c.model)return;setRunning(true);try{const b=await api.benchmark(c.model.id,['cpu','gpu','adaptive']);const done=await pollJob(b.id,()=>{});if(!done)throw new Error('Benchmark polling was cancelled');if(done.status==='failed')throw new Error(done.message||'Benchmark failed');setResults(await api.benchmarkResults(b.id))}catch(e){c.setNotice(message(e))}finally{setRunning(false)}};return <Panel title="Backend comparison" kicker="REPRODUCIBLE BENCHMARK" actions={<button disabled={!c.model||running} onClick={run}>{running?'Running…':'Run experiment'}</button>}>{results.length?<div className="comparison">{['cpu','gpu','adaptive'].map(name=>{const r=results.find(x=>x.backend===name);return <article key={name}><p className="kicker">{name.toUpperCase()}</p><h3>{r?.status||'No result'}</h3><Metric label="WALL TIME" value={r?.wall_seconds} unit="s"/><Metric label="OBJECTIVE" value={r?.objective}/><Metric label="GAP" value={r?.gap} unit="%"/><small>{r?.detail}</small></article>})}</div>:<EmptyState title="No benchmark results" detail="Run CPU, GPU, and adaptive modes on the active model. Unavailable hardware is reported by the server."/>}</Panel>}
function Verification(c:Ctx){const [result,setResult]=useState<Record<string,unknown>|null>(null);return <Panel title="Independent result checks" kicker="CERTIFICATE VERIFICATION" actions={<button disabled={!c.job||c.job.status!=='completed'} onClick={()=>setResult((c.job?.result?.verification||{}) as Record<string,unknown>)}>Show verification report</button>}>{result?<pre className="json">{JSON.stringify(result,null,2)}</pre>:<EmptyState title="No verification report" detail="Complete a solve to inspect its independent primal, bound, and certificate checks."/>}</Panel>}
function Assistant(c:Ctx){const [prompt,setPrompt]=useState(''),[proposal,setProposal]=useState<AiProposalData|null>(null),[explanation,setExplanation]=useState(''),[busy,setBusy]=useState(false);if(c.ai==='unavailable')return <Panel title="AI service unavailable" kicker="OPTIONAL SERVICE"><ServiceState service="Mistral" status="unavailable" detail="Configure the server-side integration to enable explanations. No API key belongs in this browser."/><p className="muted">Solving, benchmarking, and verification remain available without AI.</p></Panel>;const formulate=async()=>{setBusy(true);try{setProposal(await api.formulate(prompt))}catch(e){c.setNotice(message(e))}finally{setBusy(false)}};const confirm=()=>{if(!proposal?.confirmation_token){c.setNotice('The AI proposal has no valid confirmation token.');return}api.confirm(proposal.confirmation_token).then(()=>{c.setNotice('Confirmed formulation passed native model validation.');setProposal(null)}).catch(e=>c.setNotice(message(e)))};return <><div className="ai-banner"><b>MISTRAL · NON-AUTHORITATIVE</b><span>Explanations may be incomplete. Solver results and verification reports remain the source of record.</span></div><div className="two-col"><Panel title="Explain active model" kicker="READ-ONLY"><p className="muted">Request a plain-language interpretation using allowlisted model metadata.</p><button disabled={!c.model} onClick={()=>api.explain(c.model!.id).then(x=>setExplanation(x.text)).catch(e=>c.setNotice(message(e)))}>Generate explanation</button>{explanation&&<div className="explanation">{explanation}</div>}</Panel><Panel title="Draft a formulation" kicker="STRUCTURED PROPOSAL"><label>Optimization intent<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe decisions, constraints, and objective…"/></label><button disabled={!prompt.trim()||busy} onClick={formulate}>{busy?'Generating…':'Propose formulation'}</button></Panel></div>{proposal&&<AiProposal proposal={proposal} onLoad={confirm}/>}</>}
function Docs(){return <div className="docs"><Panel title="Laboratory workflow" kicker="DOCUMENTATION"><ol><li><b>Upload</b><span>Import an MPS model through the server.</span></li><li><b>Inspect</b><span>Review dimensions and compute its fingerprint.</span></li><li><b>Configure</b><span>Choose limits, tolerances, and execution backend.</span></li><li><b>Solve & observe</b><span>Follow streamed bounds, gap, nodes, and resources.</span></li><li><b>Verify</b><span>Run independent checks before using a result.</span></li></ol></Panel><Panel title="Operational boundaries" kicker="TRUST MODEL"><p>Metrics displayed here originate from the API. Empty panels mean no measurement exists. AI text is optional and non-authoritative. AI-proposed formulations require review and a separate confirmation before loading.</p><p>The browser stores no service secrets. Configure credentials and compute resources on the FastAPI server.</p></Panel></div>}
